export const actionTypes = {
    INPUT_VALUE_CHANGE: "INPUT_VALUE_CHANGE",
    INPUT_VALUE_CLEAR: "INPUT_VALUE_CLEAR",

    INIT_URL_LIST: "INIT_URL_LIST",
    REPOS_LIST_ADD: "REPOS_LIST_ADD",
    REPOS_LIST_CLEAR: "REPOS_LIST_CLEAR",
    MAXIMUM_NUMBER_FOR_RATING: "MAXIMUM_NUMBER_FOR_RATING",
    INTRODUCED_NOT_CORRECT_DATA: "INTRODUCED_NOT_CORRECT_DATA",

    SORTING_LIST_BY_FORKS: "SORTING_LIST_BY_FORKS",
    SORTING_LIST_BY_SUBSCRIBERS_COUNT: "SORTING_LIST_BY_SUBSCRIBERS_COUNT",
    CHANGE_SORTING_TYPE: "CHANGE_SORTING_TYPE",
};