export const actionTypes = {
	REPOS_LIST_ADD: "REPOS_LIST_ADD",
	REPOS_LIST_CLEAR: "REPOS_LIST_CLEAR",

	SORTING_LIST_BY_FORKS: "SORTING_LIST_BY_FORKS",
	SORTING_LIST_BY_SUBSCRIBERS_COUNT: "SORTING_LIST_BY_SUBSCRIBERS_COUNT",
};
