export const REPOS_LIST_ADD = "REPOS_LIST_ADD";
export const REPOS_LIST_CLEAR = "REPOS_LIST_CLEAR";

export const SORTING_LIST = "SORTING_LIST";
export const SORTBY_FORKS = "SORTING_LIST_BY_FORKS";
export const SORTBY_SUBSCRIBRES = "SORTBY_SUBSCRIBRES";
export const SET_SORTING_TYPE_FORKS = "SET_SORTING_TYPE_FORKS";
export const SET_SORTING_TYPE_SUBSCRIBERS = "SET_SORTING_TYPE_SUBSCRIBERS";
